version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - echo "in the install phase"
      - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
      - apt-get update && apt-get install -y jq python3-pip python3-dev && pip3 install --upgrade awscli
    finally:
      - echo This always runs even if the login command fails 
  pre_build:
    commands:
      - echo "Setting CodeCommit Credentials"
  build:
    commands:
      - echo "Build started on $(date)"
      - git clone https://github.com/awslabs/git-secrets
      - cd git-secrets
      - make install
      - cd $CODEBUILD_SRC_DIR
      - git clone https://fall.lewis+1-at-137893875086:QnJjBP+cLfghYSakcMEx29pjCCv0AGj/gd5iHhdKC5XwDQMCCfFvv0VAElE=@git-codecommit.us-east-1.amazonaws.com/v1/repos/$CODECOMMIT_REPO_NAME
      - cd $CODECOMMIT_REPO_NAME && ls -lrt
      - git secrets --install
      - git secrets --register-aws
      ## Adding additional patterns, for example password
      #- git secrets --add password\s*=\s*.+
      - git secrets --scan --recursive
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  type: zip
  files: '**/*'